version: 2.1
jobs:
  backup:
    docker:
      - image: farmsmart/gcp-firebase:1.0.0
    steps:
      - checkout
      - run: |
          echo ${GOOGLE_SERVICE_ACCOUNT} | base64 -di > ./service-account.json
          ./backup/firebase-export.sh "./service-account.json" ${FIREBASE_TOKEN} ${GOOGLE_PROJECT_ID}

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - backup:
          context: prod
